### ISSUE TITLE
Your Permalink sometimes doesn't update

### ISSUE THREAD

**Issue by alaricljs** [JordiOrlando/keyboard-layout-editor#10]
It seems that there is GUI interaction required to get the Permalink updated.  Pasting into the raw data field does not cause the Permalink to update.  Fiddling with a key property will update the permalink.

Document or fix... now that I know how to deal with it it's not a pain ;)

**Comment by jordiorlando** [comment]
This fork is temporarily/permanently on hold, so I would advise you to take a look at the [original](https://github.com/ijprest/keyboard-layout-editor) and see if the bug persists. If it does, you might file an issue there instead. Thanks!
