### ISSUE TITLE
This is an unauthorized fork, so that should be made abundantly clear

### ISSUE THREAD

**Issue by jordiorlando** [JordiOrlando/keyboard-layout-editor#9]
Perhaps a huge message that points back to the [original](keyboard-layout-editor.com) whenever someone visits this fork's [site](editor.d1sc0te.ch/kb.html). Also, this should not be posted about on the internet (reddit, GH, etc) until someone makes contact with @ijprest.

**Comment by alerque** [comment]
Have you tried contacting him off of Github? If he hasn't logged in he may just not be aware there is interest in his project. The guy has [profiles all over the internet](https://www.google.com.tr/search?q=Ian+Prest+ijprest). It looks like [his Twitter](https://twitter.com/ijprest) is dormant like his Github but the guy is alive—he was [playing on Steam](http://steamcommunity.com/id/ijprest) this week and [liking YouTube videos 5 hours ago](https://www.youtube.com/user/ijprest). It looks like [G+](https://plus.google.com/+IanPrest) or [FB](https://www.facebook.com/ijprest) might be your best contact options. Have you tried those?

**Comment by jordiorlando** [comment]
I've tried G+, Steam, and Twitter. No news yet.

**Comment by ijprest** [comment]
I'm not dead!  :)  Just been busy with other stuff.  I was aware that there were a few outstanding issues & PRs, but it looks like interest has picked up in the last month or so.  I've got a few days off work this week, so I'll make an effort to get through the backlog.

**Comment by iandoug** [comment]
@ijprest Are you SURE you're not dead.... :-)

Okay, so where does that leave us with your KLE?

Thanks, Ian

**Comment by jordiorlando** [comment]
@ijprest great news! I'm going to stop work on this fork for now, and just let me know if you'd like me to take down the live site. As for licensing stuff, I totally understand if you want to keep it under your control, in which case I might just make my own keyboard designer from scratch. As you can tell, I've already made a pretty huge mess of my fork, so that might be a good route to go. I'm glad you're back!

**Comment by ijprest** [comment]
Thanks.  I've updated my repo with more detailed license info.  I intend to eventually switch to a permissive license when the site is closer to feature-complete, but I left "all rights reserved" for now.  This is mainly to prevent a bunch of incompatible forks, which would be very easy to do, as you've discovered!  :).  

I don't mind you _running_ an experimental fork, but would prefer it to not be "advertised".  Contributions back to the main-line are encouraged, if you come up with anything cool.

**Comment by jordiorlando** [comment]
I've taken down my hosted crapfork, and if I have any changes in the future I'll make them into a proper PR on the original repo.
